#!/bin/sh
#
# bootstrap installs things.

rc=$?
if [ $rc != 0 ]; then
    exit $rc
fi
if [ -z "$1" ]; then
    os="debian" # applies to ubuntu as well
else
    os=$1
fi
. script/setup-$os
. script/setup-common

# Run the install (I'd like to pull this out of rake, eventually)
rake install
