alias agi="sudo apt-get install"
alias agr="sudo apt-get remove"
alias agu="sudo apt-get upgrade"
alias agud="sudo apt-get update"
alias agar="sudo apt-get autoremove"
alias ag="sudo apt-get update && sudo apt-get dist-upgrade -y"
